Add new quirks for SOL001 parsing
tliron/puccini pull request #58
Opened 2021-05-17 11:15 UTC by jpc4242

The new quirks are:
imports.ignore.topology_template
  ignore topology_template in imported units
substitution_mappings.requirements.allow_dangling
  allow a requirement in substitution_mapping to point to an
  undeclared requirement of a node in node_template

2021-05-19 22:03 UTC, tliron requested changes

2021-05-20 07:26 UTC, jpc4242 commented on tosca/grammars/tosca_v1_1/unit.go
> +        if context.HasQuirk(tosca.QuirkImportsIgnoreTopologyTemplate) {
Fixed in later commit

2021-05-20 07:30 UTC, jpc4242 commented on tosca/quirk.go
> +const QuirkImportsIgnoreTopologyTemplate Quirk = "imports.ignore.topology_template"
Fixed in later commit

2021-05-20 07:52 UTC, jpc4242 commented on tosca/quirk.go
> +const QuirkSubstitutionMappingsRequirementsAllowDangling Quirk = "substitution_mappings.requirements.allow_dangling"
I opened discussion at https://github.com/tliron/puccini/discussions/61

2021-06-04 15:41 UTC, tliron commented
Hi! Sorry for taking so long to review. Really the only issue is to please squash it into one commit, then we will merge.

2021-06-07 09:13 UTC, closed without merging